version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=urluser
      - DB_PASSWORD=12345
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: urluser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: